name: Code Quality


on:
    pull_request:
        branches: [main]
        paths:
            - 'src/**'
            - 'package.json'
            - 'package-lock.json'

jobs:
    lint:
        runs-on: ubantu-latest
        steps:
            - name: 检出代码
              # 检出代码的作用是获取代码库中的代码，并将其下载到工作区中。
              uses: actions/checkout@v4
              with:
                # fetch-depth: 0 表示检出完整的代码库，而不是只检出最新的提交。
                fetch-depth: 0
            - name: 设置Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'
            
            - name: 安装依赖
              run: npm ci


            - name: 运行lint
              run: npx eslint src/

            - name: 检查TypeScript类型
              if: hashFiles('tsconfig.json') != ''
              run: npx tsc --noEmit

